# %W% %G% %U%
#
# baruch makefile

SHELL=/bin/sh
#CC=gcc
#RM=rm

# flags for common K&R compiles
#
CFLAGS=-O
CC=cc

compile: src/baruch.c
	${CC} ${CFLAGS} src/baruch.c -o bin/baruch

clean:
	${RM} -f bin/*
