# %W% %G% %U%
#
# baruch makefile

SHELL=/bin/sh
CC=gcc
CP=cp
RM=rm

# flags for common K&R compiles
#
CFLAGS=-O
CC=cc

compile: baruch.c
	${CC} ${CFLAGS} baruch.c -o ../bin/baruch

clean:
	rm -f ../bin/*
